# create k8s service that expose the backend application through port 8080
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: demo-ns
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080