# create a k8s deployment for backend service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      automountServiceAccountToken: false
      containers:
      - name: backend
        image: murilobeltrame/demo-backend:latest
        env: 
          - name: ASPNETCORE_ConnectionStrings
            valueFrom: 
              secretKeyRef:
                name: backend-secrets
                key: CONNECTION_STRING
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: '1'
            memory: 200Mi
          requests:
            cpu: '0.25'
            memory: 100Mi
